name = "pixel-prop"
compatibility_date = "2024-01-01"
assets = { directory = "./dist" }

[[routes]]
pattern = "prop.domiadi.com"
custom_domain = true

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[env.production.vars]
NODE_ENV = "production"